#
# Copyright (C) 2023-2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: e2e-kubernetes-tests-main

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      organization:
        default: 'podman-desktop'
        description: 'Organization of the Podman Desktop repository'
        type: string
        required: true
      repositoryName:
        default: 'podman-desktop'
        description: 'Podman Desktop repository name'
        type: string
        required: true
      branch:
        default: 'main'
        description: 'Podman Desktop repo branch'
        type: string
        required: true
      kind_provider:
        description: 'Kind cluster provider type'
        type: choice
        options:
        - docker
        - podman
        required: true

permissions:
  contents: read

jobs:
  e2e-tests:
    name: Run All E2E tests
    runs-on: ubuntu-24.04
    # disable on forks as secrets are not available
    if: github.event.repository.fork == false
    permissions:
      checks: write # required for mikepenz/action-junit-report
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: ${{ github.event.inputs.organization }}/${{ github.event.inputs.repositoryName }}
          ref: ${{ github.event.inputs.branch }}
        if: github.event_name == 'workflow_dispatch'

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        if: github.event_name == 'push'

      - name: Set the default provider type variable
        env:
          DEFAULT_KIND_PROVIDER: 'docker'
        run: |
          echo "KIND_PROVIDER=${{ github.event.inputs.kind_provider || env.DEFAULT_KIND_PROVIDER }}" >> $GITHUB_ENV

      - name: Install Podman v5 using external action
        # Use the action from the other repository
        uses: redhat-actions/podman-install@15cb93f5a6b78a758fd8f4d1cecbf6651d4bcea3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup testenv using external action
        uses: podman-desktop/e2e/.github/actions/pde2e-testenv-prepare@13e2c57c759137bfc1f437f221967461e8a98e2a

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Execute pnpm
        run: pnpm install

      - name: Run E2E kubernetes tests in Production Mode
        env:
          PODMANDESKTOP_CI_BOT_TOKEN: ${{ secrets.PODMANDESKTOP_CI_BOT_TOKEN }}
          TEST_PODMAN_MACHINE: 'true'
          SKIP_KIND_INSTALL: 'true'
          KIND_PROVIDER_GHA: ${{ env.KIND_PROVIDER }}
          ELECTRON_ENABLE_INSPECT: true
        run: |
          echo "Compiling the Podman Desktop in production mode"
          pnpm compile:current --linux dir
          path=$(realpath ./dist/linux-unpacked/podman-desktop)
          echo "Podman Desktop built binary: $path"
          export PODMAN_DESKTOP_BINARY_PATH=$path
          pnpm test:e2e:k8s

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@e08919a3b1fb83a78393dfb775a9c37f17d8eea6 # v6.0.1
        if: always() # always run even if the previous step fails
        with:
          fail_on_failure: true
          include_passed: true
          detailed_summary: true
          annotate_only: true
          require_tests:  true
          report_paths: '**/*results.xml'

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: always()
        with:
          name: k8s-e2e-tests
          path: |
            ./tests/**/output/
            !./tests/**/traces/raw
